server {
    server_name myctc.kodedev.my.id; 

    root /var/www/myctc;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    # Menggunakan index.html sebagai file utama
    index index.html index.htm;

    charset utf-8;

    location / {
        autoindex off;
        # Mengarahkan routing fallback ke index.html (cocok untuk SPA seperti React/Vue/Angular)
        try_files $uri $uri/ /index.html;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Mengarahkan error 404 ke index.html
    error_page 404 /index.html;

    location ~ /\.(?!well-known).* {
        deny all;
    }

    
}
